;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	cider-eval-defun-at-point
	cider-load-buffer
	delete-horizontal-space
	))

(setq mc/cmds-to-run-once
      '(
	cljr-describe-refactoring
	cljr-inline-symbol
	))
